server:
  port: 8083

spring:
  application:
    name: ecall-poc-proj

  # File upload settings
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # 정적 리소스 설정
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0  # 개발 중에는 캐시 비활성화

  # 개발 편의를 위한 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  # Thymeleaf 설정 (필요시 사용)
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# Azure Speech Service 설정
azure:
  speech:
    subscription-key: ${AZURE_SPEECH_SUBSCRIPTION_KEY:YOUR_AZURE_SPEECH_KEY}
    region: ${AZURE_SPEECH_REGION:koreacentral}
    language: ${AZURE_SPEECH_LANGUAGE:ko-KR}

# 로깅 설정
logging:
  level:
    com.ecall: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"